### ISSUE TITLE
Reset stars rating to 0

### ISSUE THREAD

**Issue by nostalg33k** [evgenyneu/Cosmos#73]
Hello, 
I would like to know if there's a way to set rating to 0? What I'm trying to do is when you click on an active star, it reset the rating to zero. 
I tried to implement that by using "didTouchCosmos" or "didFinishTouchingCosmos" but I can't seem to make it work properly.

Thank you very much for this tool :)

**Comment by nostalg33k** [comment]
Ok so part of the answer was setting 
`cosmosView.settings.minTouchRating = 0`

However it still isn't the behavior I'm looking for 

> when you click on an active star, it reset the rating to zero.

 If there is no way to do that, I'll be fine with thaT.

**Comment by evgenyneu** [comment]
Hi, @nostalg33k, good question. The way Cosmos works is that it fills the star **to the point** where you touched it. For example, if you touch at the middle of the star, it will fill half of the star. If you touch at the right end of the star (for the left-to-right languages like English), it will fill the star completely. In order to empty all the stars to get zero rating you will need to touch at the start of the first star. Alternatively, one can touch at any point and then swipe in the direction of lowest rating (to the left in English).

Let me know if it helps. :)

**Comment by nostalg33k** [comment]
I understand that to get the behavior I'm looking for I would need to make changes it the way Cosmos works itself, I'll just go with swiping. Thank you for your help and quick response @evgenyneu.
