### ISSUE TITLE
can not show stars in storyboard, and crash in AppDelegate when present with Xcode debuging

### ISSUE THREAD

**Issue by foolbear** [evgenyneu/Cosmos#79]
1. Xcode 9.0, swift 4
2. setup with source file
3. iOS 11.0.1

**Comment by evgenyneu** [comment]
Thanks for letting me know @foolbear. In order to recreate your problem, I've made a demo app with a Cosmos view in the storyboard (see attached). Here is what I did.

I've dragged a View object into the storyboard and set "CosmosView" in the "class" field in the Identity Inspector. There was a weird glitch, the stars showed much lower in the storyboard relative to the actual view position. I've fixed that by removing the view and adding it again. Now the stars are shown correctly (see the screenshot). Any idea what was causing that first glitch?

<img width="200" alt="cosmos_storyboard_xcode_9" src="https://user-images.githubusercontent.com/880411/30999347-096823e2-a518-11e7-8ebe-e432880fa43b.png">

[CosmosStoryboardDemo.zip](https://github.com/evgenyneu/Cosmos/files/1342978/CosmosStoryboardDemo.zip)

**Comment by foolbear** [comment]
found issue:
1. CosmosDistrib.swift Compile failed
2. In IB, Designables: build failed!!!

**Comment by evgenyneu** [comment]
Do you see any error messages?

**Comment by foolbear** [comment]
CompileStoryboard Reading/Base.lproj/Main.storyboard
    cd /Users/foolbear/Jobs/Reading
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module Reading --output-partial-info-plist /Users/foolbear/Library/Developer/Xcode/DerivedData/Reading-bpxiwqyvxdfnmvargecfevcpkhjh/Build/Intermediates.noindex/IBDesignables/Intermediates.noindex/Reading.build/Debug-iphonesimulator/Reading.build/Main-SBPartialInfo.plist --auto-activate-custom-fonts --target-device iphone --target-device ipad --minimum-deployment-target 10.0 --output-format human-readable-text --compilation-directory /Users/foolbear/Library/Developer/Xcode/DerivedData/Reading-bpxiwqyvxdfnmvargecfevcpkhjh/Build/Intermediates.noindex/IBDesignables/Intermediates.noindex/Reading.build/Debug-iphonesimulator/Reading.build/Base.lproj /Users/foolbear/Jobs/Reading/Reading/Base.lproj/Main.storyboard

Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 255

**Comment by evgenyneu** [comment]
Thanks, I have not seen such an error before. If I were you I would Google the error message or ask on stackoverflow.

**Comment by foolbear** [comment]
ok, thanks anyway.

**Comment by foolbear** [comment]
The same error occur in your code: CosmosStoryboardDemo.

**Comment by evgenyneu** [comment]
Weird.

**Comment by evgenyneu** [comment]
Do you still have the issue?

**Comment by foolbear** [comment]
It's Xcode issue, thanks!
